name: Pack Tools

on: workflow_dispatch

jobs:
  build:
    name: Pack Tools

    strategy:
      matrix:
        target:
          - '{"rid":"win-x64","os":"windows-latest","cuda":"10.2"}'
          - '{"rid":"linux-x64","os":"ubuntu-latest","cuda":"10.2"}'
          - '{"rid":"win-x64","os":"windows-latest","cuda":"11.1"}'
          - '{"rid":"linux-x64","os":"ubuntu-latest","cuda":"11.1"}'
          - '{"rid":"win-x64","os":"windows-latest","cuda":"cpuonly"}'
          - '{"rid":"linux-x64","os":"ubuntu-latest","cuda":"cpuonly"}'
          - '{"rid":"osx-x64","os":"macos-latest","cuda":"cpuonly"}'

    runs-on: ${{ fromJson(matrix.target).os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Build and Pack
        run: ./build.cmd PackTools --configuration Release --runtime ${{ fromJson(matrix.target).rid }} --cuda-version ${{ romJson(matrix.target).cuda }}

      - name: Push Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: tools-${{ fromJson(matrix.target).rid }}-${{ romJson(matrix.target).cuda }}-${{ github.sha }}
          path: dist/depth-estimate-gui-tools.zip
